name: Run BTC Tracker Every 1 Minute

on:
  schedule:
    - cron: "*/1 * * * *"  # Every 1 minute UTC
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BTC Tracker
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python btc_tracker.py

      - name: Commit and Push Price Log
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git pull origin main
          git add btc_price_log.csv
          git commit -m "Update BTC price log" || echo "No changes to commit"
          git push origin main
