name: Run BTC Tracker Every 1 Minute

on:
  schedule:
    - cron: "*/1 * * * *"  # Every 1 minute UTC
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BTC Tracker
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python btc_tracker.py

      - name: Commit and push updated CSV file
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"
          git add btc_price_log.csv
          git commit -m "Update BTC price log"
          git push origin main
